config/routes.rb
ToDoAuth::Application.routes.draw do

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "todo_lists#index"
  resources :users
  resources :sessions
  resources :todo_lists do
   resources :todo_items
  end
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  attr_accessible :content
  validates_presence_of :content

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  belongs_to :user
  attr_accessible :description, :title
  has_many :todo_items
  validates_presence_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_hash, :password_salt, :password, :password_confirmation
  before_save :encrypt_password
  attr_accessor :password
  has_many :todo_lists

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
  user = find_by_email(email)
  if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
    user
  else
    nil
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  layout Proc.new { |controller| controller.request.xhr? ? nil : 'application' }
  before_filter :is_signed_in?
  def is_signed_in?
   unless !current_user.nil?
      redirect_to log_in_path
   end
  end

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :is_signed_in?

  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
	  session[:user_id] = nil
	  redirect_to log_in_path, :notice => "Logged out!"
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController

	def create
	 @todo_item = @todo_list.todo_items.new(params[:todo_item])
	 if @todo_item.save
	 	redirect_to @todo_list
	 end
	end

	def destroy
	 @todo_item = @todo_list.todo_items.find(params[:id])
	 if @todo_item.destroy
	  flash[:success] = "Todo List item was deleted."
	 else
	  flash[:error] = "Todo List item could not be deleted."
	 end
	 redirect_to @todo_list 
	end

	private

	def set_todo_list
	 @todo_list = TodoList.find(params[:todo_list_id])
	end

	def todo_item_params
	 params.require(:todo_item).permit(:content)
	end

	def set_todo_item
 		@todo_item = @todo_list.todo_items.find(params[:id])
	end	
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  # GET /todo_lists
  # GET /todo_lists.json
  before_filter :current_user 
  def index
    @todo_lists = TodoList.where('users_id = ?',current_user.id )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @todo_lists }
    end
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    @todo_list = TodoList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.js { render layout: false, content_type: 'text/javascript' }
      format.json { render json: @todo_list }
    end
  end

  # GET /todo_lists/new
  # GET /todo_lists/new.json
  def new
    @todo_list = TodoList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @todo_list }
    end
  end

  # GET /todo_lists/1/edit
  def edit
    @todo_list = TodoList.find(params[:id])
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    logger.debug "The current user is  "+ current_user.id.to_s  # This fails . Says the class in nil

    @todo_list = TodoList.new(params[:todo_list])
    @todo_list.users_id = current_user.id;

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render json: @todo_list, status: :created, location: @todo_list }
      else
        format.html { render action: "new" }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /todo_lists/1
  # PUT /todo_lists/1.json
  def update
    @todo_list = TodoList.find(params[:id])

    respond_to do |format|
      if @todo_list.update_attributes(params[:todo_list])
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list = TodoList.find(params[:id])
    @todo_list.destroy

    respond_to do |format|
      format.html { redirect_to todo_lists_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :is_signed_in?
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to log_in_path, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def index
   @user = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoAuth</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="user_nav" style="text-align: right;">
    <% if current_user %>
      Logged in as <%= current_user.email %>
      <%= link_to "Log out", log_out_path %>
    <% end %>
  </div>
<div class="container">
  <%= yield %>
</div>
<div id="modal-holder"></div>

</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
 <%= f.text_field :content, placeholder: "New Todo" %>
 <%= f.submit:"Create To do Item", class:"btn btn-primary" %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix">
  <div class="todo_item">
  	 <p><%= todo_item.content %></p>
  </div>
  <div class="trash">
   <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
    <i class="fa fa-2x fa-trash"></i>
   <% end %>
  </div>
</div>   

app/views/todo_lists/_form.html.erb
<%= stylesheet_link_tag "todo_lists" %>
<%= stylesheet_link_tag "app" %>
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit:'Create To Do List', class: 'btn btn-primary createBtn' %>
    <%= link_to 'Back', todo_lists_path, class:"btn btn-primary linkBack" %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1 class="todo_list_title">Editing Todo List</h1>
<div class="forms">
<%= render 'form', todo_list: @todo_list %>
</div>

app/views/todo_lists/index.html.erb
<%= stylesheet_link_tag "todo_lists" %>
<%= stylesheet_link_tag "app" %>
<% @todo_lists.each do |todo_list| %>
<div class="index_row clearfix">
  <div class="col-md-3"><span class="todo_list_sub_title"><%= todo_list.title %></span></div>
  <div class="col-md-5"><span class="todo_list_sub_title"><%= todo_list.description %></span></div>
   <div class="col-md-1">
	<%= link_to todo_list, title:"View" do %>
    	<i class="fa fa-eye fontAwe" aria-hidden="true"></i>
    <% end %>
   	</div>
   <div class="col-md-1">
    <%= link_to edit_todo_list_path(todo_list), title:"Edit" do %>
    	<i class="fa fa-pencil-square-o fontAwe" aria-hidden="true"></i>
    <% end %>
   	</div>
   <div class="col-md-1">
   	<%= link_to todo_list, method: :delete, data: { confirm: 'Are you sure?' }, title:"Delete" do %>
    	<i class="fa fa-trash fontAwe" aria-hidden="true"></i>
    <% end %>
   	</div>
</div>
<% end %>
<br />
<div style="margin-left: 40px">
<%= button_to "Create To do List", new_todo_list_path, method: :get, class:"createBtn" %></div>
<div id='post-content'></div>

app/views/todo_lists/new.html.erb
<%= stylesheet_link_tag "app" %>

<h1 class="todo_list_title">New Todo List</h1>
	<div class="forms">
	<%= render 'form', todo_list: @todo_list %>
	</div>
	<div class="links">
</div>

app/views/todo_lists/show.html.erb
<%= stylesheet_link_tag "app" %>
<%= stylesheet_link_tag "todo_lists" %>
<div style="margin-left: 20px">
	<p id="notice"><%= notice %></p>

	<h3>
	  <%= @todo_list.title %>
	</h3>

	<p style="font-size:15px;">
	  <b>Description:</b>
	  <%= @todo_list.description %>
	</p>

	<div id="todo_items_wrapper">
	 <table>
	 	<%= render @todo_list.todo_items %>
	</table>
	 <div id="form">
	  <%= render "todo_items/form" %>
	 </div>
	</div>
	<%= button_to "Edit", edit_todo_list_path(@todo_list), class:"btn btn-primary btn", method: :get, form: {style: 'display:inline-block;'} %>
	<%= button_to "Back", todo_lists_path, class:"btn btn-primary btn", method: :get, form: {style: 'display:inline-block;float:right;margin-right:32px;'} %>
</div>

app/views/users/new.html.erb
<%= stylesheet_link_tag "users" %>
<div class="container">
  <div class="row main">
    <div class="panel-heading">
      <div class="panel-title text-center">
        <h3 class="title">Sign Up</h3>
      </div>
  </div> 
  <div class="main-login main-center">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
            <div class ="alert alert-info">
              <% for message in @user.errors.full_messages %>
                <li><%=message%></li>
              <% end %>
            </div>
      <% end %>
      <p>
        <%= f.text_field :email, placeholder: "Email" %>
      </p>
      <p>
        <%= f.password_field :password, placeholder: "Password"  %>
      </p>
      <p>
        <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
      </p>
      <p class="submit-btn"><%= f.submit:Submit, class: 'btn btn-primary' %></p>
      <div class="signLink"><%= link_to "Already have an account? Login In", log_in_path %> </div>
    <% end %>
  </div>
</div>